fix arabic translation error
education/GitHubGraduation-2022 pull request #5246
Opened 2022-05-10 20:30 UTC by FnrDev

# Arabic Translation🎓

This pull request, fix the translation error for the word short name, it has been changed from "فصير" to "قصير"

## Checklist ✅

- [ ] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [ ] I understand I should not tag or add a reviewer to this Pull Request.

2022-05-10 20:31 UTC, github-education requested changes
**Hi FnrDev,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *I'm not seeing a valid student developer pack approval, please submit an [application](https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation) to get started*
* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/FnrDev/FnrDev.md` exists*
*Please ensure all changes are contained within the `_data/FnrDev/` directory. Invalid file paths:* 

	* `translations/README.ar.md`


Feel free to re-request a review from me and I'll come back and take a look!

2022-05-16 18:51 UTC, FnrDev commented
Hey @elisemoe can you review this PR

Thanks you

2022-06-04 03:03 UTC, juanpflores approved these changes

2022-06-04 03:03 UTC, juanpflores commented
Thanks for your contribution!

2022-06-04 03:03 UTC, merged